# Home task: pandas 

## Question 1

- Load the energy data from the file [Energy Indicators.xls](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls).
It is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013.


- It should be put into a DataFrame with the variable name of "energy"


- Make sure to exclude the footer and header information from the datafile.


- The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:<br>
`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`


- Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule).


- For all countries which have missing data (e.g. data with `...`) make sure this is reflected as `np.NaN` values.


- Rename the following list of countries (for use in later questions):
    - `Republic of Korea`: `South Korea`,
    - `United States of America`: `United States`,
    - `United Kingdom of Great Britain and Northern Ireland`: `United Kingdom`,
    - `China, Hong Kong Special Administrative Region`: `Hong Kong`


- There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g.:
    - `Bolivia (Plurinational State of)` should be `Bolivia`,
    - `Switzerland17` should be `Switzerland`.


- Next, load the GDP data from the file ["world_bank.csv"](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). 
It is a csv containing countries' GDP from 1960 to 2015 from World Bank. Call this DataFrame "GDP"


- Make sure to skip the header, and rename the following list of countries:
    - `Korea, Rep.`: `South Korea`,
    - `Iran, Islamic Rep.`: `Iran`,
    - `Hong Kong SAR, China`: `Hong Kong`


- Finally, load the "Sciamgo Journal and Country Rank data for [Energy Engineering and Power Technology"](http://www.scimagojr.com/countryrank.php?category=2102). It ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame "ScimEn"


- Join the three datasets: Energy, GDP, and ScimEn into a new dataset (using the intersection of country names). Use only the 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).


- The index of this DataFrame should be the name of the country, and the columns should be<br>
`['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', 2012', '2013', '2014', '2015']`

Function "answer_one" should return the resulted DataFrame (20 columns and 15 entries)

<h2>1 Task</h2> <h4>Load the energy data from the file Energy Indicators.xls. It is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013.</h4>

<p>-It should be put into a DataFrame with the variable name of "energy"</p>

<p>-Make sure to exclude the footer and header information from the datafile.</p>

In [7]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [193]:
import pandas as pd
import numpy as np
energy_df=pd.read_excel('Energy Indicators.xls')

In [194]:
energy_df = energy_df.iloc[17:244].drop(energy_df.columns[:2], axis=1)

<h4>The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:<br>
`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`</h4>

In [195]:
energy_df.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [196]:
energy_df.head(5)

           Country Energy Supply Energy Supply per Capita % Renewable
17     Afghanistan           321                       10    78.66928
18         Albania           102                       35         100
19         Algeria          1959                       51     0.55101
20  American Samoa           ...                      ...    0.641026
21         Andorra             9                      121    88.69565

<h4>Convert Energy Supply to gigajoules (there are 1,000,000 gigajoules in a petajoule).</h4>

In [197]:
energy_df['Energy Supply'] = energy_df['Energy Supply'] * 1000000
energy_df.head()

,Country,Energy Supply,Energy Supply per Capita,% Renewable
17,Afghanistan,321000000,10,78.66928
18,Albania,102000000,35,100
19,Algeria,1959000000,51,0.55101
20,American Samoa,.................................................,...,0.641026
21,Andorra,9000000,121,88.69565

<h4>For all countries which have missing data (e.g. data with ...) make sure this is reflected as np.NaN values.</h4>

In [200]:
energy_df = energy_df.replace(r'^\.+$', np.nan, regex=True)
energy_df = energy_df.infer_objects(copy=False)
energy_df = energy_df.apply(lambda col: pd.to_numeric(col, errors='coerce') if col.name != 'Country' else col)
energy_df['Energy Supply'] = energy_df['Energy Supply'].astype('Int64')

In [201]:
energy_df.head()

           Country  Energy Supply  Energy Supply per Capita  % Renewable
17     Afghanistan      321000000                      10.0    78.669280
18         Albania      102000000                      35.0   100.000000
19         Algeria     1959000000                      51.0     0.551010
20  American Samoa           <NA>                       NaN     0.641026
21         Andorra        9000000                     121.0    88.695650

In [202]:
energy_df.isna().sum()

Country                     0
Energy Supply               5
Energy Supply per Capita    5
% Renewable                 0
dtype: int64

<h4>Rename the following list of countries (for use in later questions):</h4>
<ul><li>Republic of Korea: South Korea,</li>
<li>United States of America: United States,</li>
<li>United Kingdom of Great Britain and Northern Ireland: United Kingdom,</li>
<li>China, Hong Kong Special Administrative Region: Hong Kong</li></ul>

In [214]:
energy_df['Country'] = energy_df['Country'].replace({
    'Republic of Korea': 'South Korea',
    'United States of America': 'United States',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'China, Hong Kong Special Administrative Region': 'Hong Kong'
})

In [215]:
energy_df.loc[energy_df['Country'] == 'South Korea']

         Country  Energy Supply  Energy Supply per Capita  % Renewable
181  South Korea    11007000000                     221.0     2.279353

In [216]:
energy_df.loc[energy_df['Country'] == 'United States']

           Country  Energy Supply  Energy Supply per Capita  % Renewable
233  United States    90838000000                     286.0     11.57098

In [217]:
energy_df.loc[energy_df['Country'] == 'United Kingdom']

            Country  Energy Supply  Energy Supply per Capita  % Renewable
231  United Kingdom     7920000000                     124.0     10.60047

In [218]:
energy_df.loc[energy_df['Country'] == 'Hong Kong']

      Country  Energy Supply  Energy Supply per Capita  % Renewable
60  Hong Kong      585000000                      82.0          0.0

<h4>There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g.:</h4>

<ul><li>Bolivia (Plurinational State of) should be Bolivia,</li>
<li>Switzerland17 should be Switzerland.</li></ul>

In [219]:
energy_df['Country'] = energy_df['Country'].str.replace(r'\s*\(.*\)|\d+', '', regex=True).str.strip()

In [220]:
energy_df.loc[energy_df['Country'] == 'Bolivia']

    Country  Energy Supply  Energy Supply per Capita  % Renewable
41  Bolivia      336000000                      32.0     31.47712

In [221]:
energy_df.loc[energy_df['Country'] == 'Switzerland']

         Country  Energy Supply  Energy Supply per Capita  % Renewable
214  Switzerland     1113000000                     136.0     57.74548

<h4>Next, load the GDP data from the file "world_bank.csv". It is a csv containing countries' GDP from 1960 to 2015 from World Bank. Call this DataFrame "GDP"</h4>

In [222]:
GDP = pd.read_excel('world_bank.xls', skiprows=3)
GDP.rename(columns = {'Country Name': 'Country'}, inplace = True)

In [223]:
GDP.head(5)

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.276188e+09,3.395794e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.112502e+10,2.161623e+10,2.350628e+10,2.804836e+10,2.592067e+10,2.947210e+10,...,9.859871e+11,1.006526e+12,9.273485e+11,8.851764e+11,1.021043e+12,1.007196e+12,1.000834e+12,9.275933e+11,1.081998e+12,1.169484e+12
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,2.056449e+10,2.055058e+10,1.999814e+10,1.801955e+10,1.889635e+10,1.841886e+10,1.890450e+10,2.014345e+10,1.458314e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.044764e+10,1.117321e+10,1.199053e+10,1.272769e+10,1.389811e+10,1.492979e+10,...,8.339481e+11,8.943225e+11,7.686447e+11,6.913634e+11,6.848988e+11,7.670257e+11,8.225384e+11,7.864600e+11,8.444597e+11,8.778633e+11
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.024137e+10,6.568544e+10,1.067136e+11

- Make sure to skip the header, and rename the following list of countries:
    - `Korea, Rep.`: `South Korea`,
    - `Iran, Islamic Rep.`: `Iran`,
    - `Hong Kong SAR, China`: `Hong Kong`

In [224]:
GDP['Country'] = GDP['Country'].replace({
    'Korea, Rep.': 'South Korea',
    'Iran, Islamic Rep.': 'Iran',
    'Hong Kong SAR, China': 'Hong Kong'
})

In [225]:
GDP.loc[GDP['Country'] == 'South Korea']

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
126,South Korea,KOR,GDP (current US$),NY.GDP.MKTP.CD,3.958824e+09,2.417638e+09,2.814626e+09,3.988477e+09,3.459033e+09,3.120871e+09,...,1.370795e+12,1.484318e+12,1.465773e+12,1.500112e+12,1.623901e+12,1.724846e+12,1.651423e+12,1.644313e+12,1.810956e+12,1.665246e+12

- Finally, load the "Sciamgo Journal and Country Rank data for [Energy Engineering and Power Technology"](http://www.scimagojr.com/countryrank.php?category=2102). It ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame "ScimEn"

In [226]:
ScimEn = pd.read_excel(
    'scimagojr country rank 1996-2024.xlsx',  
    engine='openpyxl'
)

In [227]:
ScimEn

,Rank,Country,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246
...,...,...,...,...,...,...,...,...,...
209,210,Montserrat,Latin America,1,1,9,0,9.00,1
210,211,Dominica,Latin America,1,1,1,0,1.00,1
211,212,Christmas Island,Pacific Region,1,1,0,0,0.00,0
212,213,Guinea-Bissau,Africa,1,1,55,7,55.00,1
213,214,Marshall Islands,Pacific Region,1,1,1,0,1.00,1

- Join the three datasets: Energy, GDP, and ScimEn into a new dataset (using the intersection of country names). Use only the 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

In [228]:
GDP_New = GDP[['Country'] + list(GDP.loc[:, '2006':'2015'])]

In [229]:
display(GDP_New)

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,2.469832e+09,2.677654e+09,2.843017e+09,2.553631e+09,2.453631e+09,2.637989e+09,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09
1,Africa Eastern and Southern,5.775869e+11,6.628680e+11,7.105362e+11,7.219012e+11,8.635195e+11,9.678246e+11,9.753548e+11,9.859871e+11,1.006526e+12,9.273485e+11
2,Afghanistan,6.971383e+09,9.715765e+09,1.024977e+10,1.215484e+10,1.563384e+10,1.819041e+10,2.020357e+10,2.056449e+10,2.055058e+10,1.999814e+10
3,Africa Western and Central,3.969210e+11,4.654855e+11,5.677912e+11,5.083627e+11,5.985216e+11,6.820159e+11,7.375895e+11,8.339481e+11,8.943225e+11,7.686447e+11
4,Angola,5.238103e+10,6.526642e+10,8.853866e+10,7.030720e+10,8.169953e+10,1.094366e+11,1.249982e+11,1.334016e+11,1.372444e+11,8.721930e+10
...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,NaN,NaN,5.181777e+09,5.015895e+09,5.343951e+09,6.341615e+09,6.163483e+09,6.735328e+09,7.074393e+09,6.295845e+09
262,"Yemen, Rep.",1.906198e+10,2.165053e+10,2.691086e+10,2.513028e+10,3.090675e+10,3.272642e+10,3.540132e+10,4.041523e+10,4.322859e+10,4.244449e+10
263,South Africa,3.038587e+11,3.330771e+11,3.161312e+11,3.297541e+11,4.173638e+11,4.581995e+11,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11
264,Zambia,1.275686e+10,1.405696e+10,1.791086e+10,1.532834e+10,2.026556e+10,2.345952e+10,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10
265,Zimbabwe,5.443896e+09,5.291950e+09,4.415703e+09,9.665793e+09,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10

In [230]:
ScimEn_15 = ScimEn[ScimEn['Rank'] <= 15]

In [231]:
ScimEn_15

,Rank,Country,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246
5,6,Germany,Western Europe,55466,54296,932195,185376,16.81,274
6,7,Russian Federation,Eastern Europe,49938,49562,268391,112125,5.37,123
7,8,Canada,Northern America,44877,44004,1082361,161133,24.12,305
8,9,Italy,Western Europe,42635,40695,767280,171442,18.00,227
9,10,South Korea,Asiatic Region,42534,42174,761076,124789,17.89,215
10,11,Iran,Middle East,35889,35484,798505,211983,22.25,218
11,12,France,Western Europe,33407,32698,637552,99244,19.08,235
12,13,Spain,Western Europe,32521,31781,726414,118758,22.34,233
13,14,Australia,Pacific Region,31047,30232,760284,99637,24.49,262
14,15,Brazil,Latin America,30840,30383,371926,84223,12.06,167

- The index of this DataFrame should be the name of the country, and the columns should be<br>
`['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', 2012', '2013', '2014', '2015']`

In [232]:
merged_data = pd.merge(ScimEn_15[['Rank', 'Country', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index']], GDP_New, on='Country', how='inner')

In [233]:
answer_one= pd.merge(energy_df, merged_data, on='Country', how='inner')

In [234]:
answer_one_rank=answer_one.iloc[:, 1:]

In [235]:
answer_one_rank.sort_values(by='Rank')

,Energy Supply,Energy Supply per Capita,% Renewable,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
3,127191000000,93.0,19.754910,1,472465,470142,6591474,4594673,13.95,380,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551545e+12,8.532186e+12,9.570471e+12,1.047562e+13,1.106157e+13
14,90838000000,286.0,11.570980,2,222772,217929,4131736,1119917,18.55,491,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
6,33195000000,26.0,14.969080,3,96975,94714,1243636,479638,12.82,258,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856721e+12,2.039126e+12,2.103588e+12
13,7920000000,124.0,10.600470,4,61946,60287,1326766,207337,21.42,313,2.709978e+12,3.092996e+12,2.931684e+12,2.417566e+12,2.491397e+12,2.666403e+12,2.706341e+12,2.786315e+12,3.065223e+12,2.934858e+12
9,18984000000,149.0,10.232820,5,61939,61307,813472,166907,13.13,246,4.601663e+12,4.579750e+12,5.106679e+12,5.289494e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
5,13261000000,165.0,17.901530,6,55466,54296,932195,185376,16.81,274,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
11,30709000000,214.0,17.288680,7,49938,49562,268391,112125,5.37,123,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
2,10431000000,296.0,61.945430,8,44877,44004,1082361,161133,24.12,305,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
8,6530000000,109.0,33.667230,9,42635,40695,767280,171442,18.00,227,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
10,11007000000,221.0,2.279353,10,42534,42174,761076,124789,17.89,215,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
7,9172000000,119.0,5.707721,11,35889,35484,798505,211983,22.25,218,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
4,10597000000,166.0,17.020280,12,33407,32698,637552,99244,19.08,235,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
12,4923000000,106.0,37.968590,13,32521,31781,726414,118758,22.34,233,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324751e+12,1.355580e+12,1.371821e+12,1.196157e+12
0,5386000000,231.0,11.810810,14,31047,30232,760284,99637,24.49,262,7.479074e+11,8.544273e+11,1.055686e+12,9.286298e+11,1.148570e+12,1.398456e+12,1.546953e+12,1.576330e+12,1.467590e+12,1.350580e+12
1,12149000000,59.0,69.648030,15,30840,30383,371926,84223,12.06,167,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 2
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [236]:
def answer_two():
    Top15 = answer_one
    Top15['Average GDP'] = Top15.loc[:, '2006':'2015'].mean(axis=1, skipna=True)
    avgGDP = Top15[['Country', 'Average GDP']].sort_values(by=['Average GDP']).iloc[::-1]
    return avgGDP
answer_two()

               Country   Average GDP
14       United States  1.570403e+13
3                China  6.927707e+12
9                Japan  5.239642e+12
5              Germany  3.523342e+12
13      United Kingdom  2.780276e+12
4               France  2.691337e+12
8                Italy  2.142986e+12
1               Brazil  1.988889e+12
11  Russian Federation  1.666746e+12
2               Canada  1.616359e+12
6                India  1.602352e+12
12               Spain  1.400886e+12
10         South Korea  1.221372e+12
0            Australia  1.207513e+12
7                 Iran  4.563261e+11

### Question 3
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [237]:
answer_two().iloc[5]

Country                      France
Average GDP    2691336579143.643555
Name: 4, dtype: object

In [238]:
def answer_three():
    Top15 = answer_two()
    country = Top15.iloc[5]['Country']
    df = answer_one.set_index('Country')
    
    return pd.DataFrame({
        'Country': [country],
        'GDP Change': [df.loc[country, '2015'] - df.loc[country, '2006']]
    })
answer_three()

  Country    GDP Change
0  France  1.186524e+11

### Question 4

Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [239]:
def answer_four():
    Top15 = answer_one
    Top15["Self-Citation"] = Top15["Self-citations"] / Top15["Citations"]
    max_country = Top15.loc[Top15["Self-Citation"].idxmax()]
    return (max_country["Country"], float(max_country["Self-Citation"]))
answer_four()

('China', 0.6970630544852335)

### Question 5

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [240]:
def answer_five():
    Top15 = answer_one
    Top15['Population'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    return Top15[['Country', 'Population']].sort_values(
        by='Population', ascending=False).iloc[2]
answer_five()

Country          United States
Population    317615384.615385
Name: 14, dtype: object

### Question 6
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

In [241]:
def answer_six():
    Top15 = answer_one
    Top15["CD per capita"] = Top15["Citable documents"] / Top15["Population"]
    return float(Top15["CD per capita"].corr(Top15["Energy Supply per Capita"]))
answer_six()

0.6905473831164103

### Question 7
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [252]:
def answer_seven():
    Top15 = answer_one
    
    ContinentDict = {
        'China': 'Asia', 
        'United States': 'North America', 
        'Japan': 'Asia', 
        'United Kingdom': 'Europe', 
        'Russian Federation': 'Europe', 
        'Canada': 'North America', 
        'Germany': 'Europe', 
        'India': 'Asia',
        'France': 'Europe', 
        'South Korea': 'Asia', 
        'Italy': 'Europe', 
        'Spain': 'Europe', 
        'Iran': 'Asia',
        'Australia': 'Australia', 
        'Brazil': 'South America'
    }
    
    Top15['Continent'] = Top15['Country'].map(ContinentDict)
    
    return Top15.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std'])

In [253]:
answer_seven()

               size               sum              mean               std
Continent
Asia              5   2898666386.6106   579733277.32212  679097888.366095
Australia         1   23316017.316017   23316017.316017              <NA>
Europe            6  457929667.216372   76321611.202729   34647667.065623
North America     2   352855249.48025  176427624.740125  199669644.856668
South America     1  205915254.237288  205915254.237288              <NA>